version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/waitinglist_db
      SPRING_DATASOURCE_USERNAME: hamza
      SPRING_DATASOURCE_PASSWORD: hamza

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: waitinglist_db
      POSTGRES_USER: hamza
      POSTGRES_PASSWORD: hamza
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: