spring:
  datasource:
    url: jdbc:postgresql://db:5432/waitinglist_db
    username: hamza
    password: hamza
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true