spring:
  application:
    name: BACKEND

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/waitinglist_db
    username: hamza
    password: hamza
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, validate, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always